### ISSUE TITLE
Inconsistent Shapechanger handling

### ISSUE THREAD

**Issue by SleeplessOne1917** [bagelbits/5e-database#467]
I noticed that we handle vampires, which are shapechangers, different than other shapechangers (e.g. werebears, wereboars, etc.). Instead of having separate entries for its different forms, we have it's actions labeled "(Vampire form only)" or something similar. Should vampire be broken up into separate entries like the other shapechangers?

I also noticed the wererat human form's multiattack is named "Multiattack (Humanoid or Hybrid Form Only)". This is inconsistent with the other shapechangers, where it's just called "Multiattack" and is omitted from the forms that can't use it.

**Comment by bagelbits** [comment]
For vampires, I think splitting it up makes sense.

For Wererat, Good Catch! That should be cleaned up.

**Comment by bagelbits** [comment]
If you feel up to opening a PR, I'm happy to review it. I'm sick right now, so it'll be a little bit before I can cut a PR myself.

**Comment by SleeplessOne1917** [comment]
@bagelbits I noticed someone reporting an issue with this in the bugs channel in discord. With [the PR](https://github.com/5e-bits/5e-database/pull/473) merged, you can query the individual forms of vampire (e.g. `/api/monsters/vampire-vampire`) just fine, and `/api/monster/vampire` no longer returns a result. However, when you query `/api/monsters` to get the list of APIReferences, the forms don't show up but the monster with `index = vampire` does. After looking at the API's source code, my first guess is that the API is using an out of date redis cache. I believe the cache needs to be invalidated somehow before we can close this issue.

**Comment by bagelbits** [comment]
I think it was a temporary cache issue. It's cleared up now.
