### ISSUE TITLE
Innate spellcasting missing required components

### ISSUE THREAD

**Issue by Rarst** [bagelbits/5e-database#475]
The most common components note for innate spellcasting is `requiring no material components` and the data for it is an empty array `"components_required": []`.

I think this should be `["V","S"]` since nothing is said about verbal and somatic, thus they are still required?

For comparison `requiring only verbal components` is captured in data as `components_required": ["V"]`.

Relevant Jeremy Crawford tweet:

>\- innate spellcasting doesn't require material components. Verbal and somatic?
>\- Casting a spell requires all its components unless a trait or feature says otherwise.
>
> https://twitter.com/JeremyECrawford/status/606207225334530048

**Comment by bagelbits** [comment]
I think you're right. Good catch! Feel free to cut a PR if you want to fix this.
