### ISSUE TITLE
Monster variants in data that are not SRD content

### ISSUE THREAD

**Issue by Rarst** [bagelbits/5e-database#476]
I have noticed that Djinni data has `Variant: Genie Powers`, which doesn't seem to be part of SRD, that variant appears in Monster Manual.

From quick search of `variant` I get 22 hits in monster data, while only 2 hits in SRD for monsters.

**Comment by bagelbits** [comment]
Oh you're right. That should get cleaned up. Good catch! Feel free to open a PR if you like.
