### ISSUE TITLE
GitHub deploy action trying to run in a fork

### ISSUE THREAD

**Issue by Rarst** [bagelbits/5e-database#478]
I've noticed that I got a failing GitHub deploy action in my fork, when working on PR.

Seems like it would make sense if any action of such kind was restricted to the original repo?

**Comment by bagelbits** [comment]
That's a good point. I'm not entirely sure how to do that but I bet it's documented somewhere. If you want to take a stab, feel free to open a PR but I'll can take a look later.

**Comment by fergcb** [comment]
Could we just add a condition to the workflows?

```yml
  if: github.repository == '5e-bits/5e-database'
```

**Comment by Rarst** [comment]
Not very fluent with Actions to sort out what's going on, but here is docs link for that:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository

**Comment by bagelbits** [comment]
Let me throw together a quick PR for both repos.

**Comment by bagelbits** [comment]
Okay. I think that should do it?

**Comment by bagelbits** [comment]
Can someone sanity check me?
