### ISSUE TITLE
1.2.6 tag missing in main branch

### ISSUE THREAD

**Issue by Rarst** [bagelbits/5e-database#484]
I've noticed that my fork's main got de-synced from upstream in couple of commits and had to do reset/force push.

Following that I noticed that I can't seem to fetch 1.2.6 tag, though that release exists upstream.

Looking up the 1.2.6 commit in GitHub releases leads to https://github.com/5e-bits/5e-database/commit/2580b7f4023aadb7a796a89562c1a0617e0fbcb0 which says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Sounds like 1.2.6 tag got very very lost somehow? :)

**Comment by bagelbits** [comment]
Yeah sorry about that. A previous commit messed up because the commit message was wrong. So I cleaned it up. Looks like something was still failing so I'm trying to fix it up.

**Comment by bagelbits** [comment]
Fixed it!
