### ISSUE TITLE
Missing monster flavor text

### ISSUE THREAD

**Issue by Rarst** [bagelbits/5e-database#485]
In D&D books there is usually some flavor text in addition to a stat block. In SRD this part seems to have been (mostly?) stripped from _monster_ monsters, but some misc creatures and NPCs still have it. This does not seem to be currently captured in data (at least not for a single one I spot checked). See Archmage for example.

I can do a pass on this some time, just where exactly it should go? 
1. `desc` on a monster root? Where in order of properties?
2. As a markdown string or array of paragraphs?
3. Keeping formatting (name of the monster is usually bolded in SRD) or plain text?

**Comment by bagelbits** [comment]
1. Yeah `desc` on a monster root
2. Markdown string please. I think that's what we're trying to do. See rules as a good example
3. Keep formatting since it's Markdown
