### ISSUE TITLE
Minor errors found in spell data

### ISSUE THREAD

**Issue by LukeLay** [bagelbits/5e-database#556]
-Druid 6th level spell "Find the Path" exists in PHB and SRD but Druid is not listed in the classes for it in the API
-Guardian of Faith spell lists Paladin in the classes on API but is not present in PHB or SRD
-Hunter's Mark spell lists Paladin in the classes on API but is not present in PHB or SRD

**Comment by bagelbits** [comment]
@LukeLay Let me know if that fixes everything!
