### ISSUE TITLE
Missing Background Data in DnD 5th Edition API

### ISSUE THREAD

**Issue by zbzxx** [bagelbits/5e-database#755]
When attempting to retrieve all background data for D&D 5th Edition using the following API endpoint:
GET https://www.dnd5eapi.co/api/backgrounds,
only the Acolyte background is returned.

## Expected Behavior:
The endpoint should return a comprehensive list of all available backgrounds as defined in the D&D 5th Edition ruleset.

## Observed Behavior:
The response contains data for the Acolyte background only, with the majority of background data missing.

## Steps to Reproduce:

1. Send a GET request to https://www.dnd5eapi.co/api/backgrounds.
2. Observe the response containing only the Acolyte background.

## Investigation Notes:

Upon further investigation, it appears that the database JSON file powering the API is missing a significant portion of background data. This is likely the root cause of the issue.

## Suggested Action:

- Verify and restore the missing background entries in the database.
- Ensure the API response includes all expected backgrounds.

**Comment by fergcb** [comment]
The API only includes data from the SRD. This is the only data we're legally allowed to distribute. Check our FAQ for more info https://5e-bits.github.io/docs/faq#a-monster-spell-subclass-etc-is-missing-from-the-api--database-can-i-add-it
